#ifndef FDD3000AXISVIS_h
#pragma once
#define FDD3000AXISVIS_h

#define _FDD3000AXISVIS_MAXLOGBUFFER_ENTRIES      101   //maximal log buffer entries
#define _FDD3000AXISVIS_LOGBUFFER_VISIBLEENTRIES    5   //maximal visible log entries
#define _FDD3000AXISVIS_MAXLOG_OFFSET             (_FDD3000AXISVIS_MAXLOGBUFFER_ENTRIES-_FDD3000AXISVIS_LOGBUFFER_VISIBLEENTRIES)

#endif
