//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
TYPE
#pragma pack(push, 1)
  _BasicCanObj : STRUCT
    CanData : ARRAY [0..7] OF USINT;
    length : USINT;  //! <Type Comment="datalength of object" Name="_BasicCanObj.length"/>
    objnumber : UDINT;  //! <Type Comment="objectnumber" Name="_BasicCanObj.objnumber"/>
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  _ComSDO : STRUCT
    hdTxRxResult : HDINT;
    dTxCounter : DINT;
    dRxCounter : DINT;
    dErrCounter : DINT;
    hdLastErrCode : HDINT;
    hdErrIndex : HDINT;
    hdErrSubIndex : HDINT;
    hdErrData : HDINT;
    dErrRW : DINT;
    dErrLen : DINT;
  END_STRUCT;
#pragma pack(pop)
  _DISPLAYDUMMY : ARRAY [0..699] OF CHAR;
  _DRIVETYPE :
  (
    _NotFound,
    _SDD_310,
    _SDD_315,
    _SDD_105,
    _SDD_120,
    _SDD_305,
    _SDD_335,
    _SDD_215,
    _SDD_205,
    _SDD_210,
    _MDD_100,
    _S_340,
    _SDD_115,
    _SDD_1300:=811237,
    _SDD_1400:=811238,
    _SDD_1500:=811239,
    _SDD_1600:=811240,
    _MDD_2000:=811300,
    _VSDC_151:=811301,
    _DC061:=881042,
    _DC062:=881801,
    _SR011:=881802,
    _SR012:=881803,
    _DC101:=881804,
    _DC102:=881805,
    _WA011:=991800,
    _WA012:=991801
  )$UDINT;
#pragma pack(push, 1)
  _I_HC_Type : STRUCT  //! <Type Comment="Hardware Code an axis&#13;&#10;&#13;&#10;Bit 31..16 Hardware Code of the Control Board&#13;&#10;Bit 15...8 Software version of the feedback CPLD&#13;&#10;Bit   7...0 Hardware Code of the Power Stage" Name="_I_HC_Type"/>
    HardwareCodePowerStage : HSINT;  //! <Type Comment="Hardware Code of the Power Stage (Default: 16#80)" Name="_I_HC_Type.HardwareCodePowerStage"/>
    FPGAVersion : HSINT;  //! <Type Comment="Software version of the feedback CPLD" Name="_I_HC_Type.FPGAVersion"/>
    HardwareCodeControlBoard : HINT;  //! <Type Comment="Hardware Code of the Control Board (Default: 16#0000)" Name="_I_HC_Type.HardwareCodeControlBoard"/>
  END_STRUCT;
#pragma pack(pop)
  _KEYBUFFER : ARRAY [0..31] OF DINT;
#pragma pack(push, 1)
  _KEYS_DATA : STRUCT
    ud_no : UDINT;
    bd_bitcode : BDINT
    [
    ];
    keybuffer_pressed : _KEYBUFFER;
    keybuffer_new : _KEYBUFFER;
    keybuffer_gone : _KEYBUFFER;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  _LEDS_DATA : STRUCT
    bd_ledson : BDINT
    [
    ];
    bd_ledsblinking : BDINT
    [
    ];
    ud_ledsblinkingtime : UDINT;
  END_STRUCT;
#pragma pack(pop)
  _LSLONL_STATUS_PLC :
  (
    LSLONL_RUN_RAM:=0,
    LSLONL_RUN_ROM:=1,
    LSLONL_RUNTIME:=2,
    LSLONL_POINTER:=3,
    LSLONL_CHKSUM:=4,
    LSLONL_WATCHDOG:=5,
    LSLONL_GENERAL_ERROR:=6,
    LSLONL_PROM_DEFECT:=7,
    LSLONL_RESET:=8,
    LSLONL_WD_DEFECT:=9,
    LSLONL_STOP:=10,
    LSLONL_PROG_BUSYS:=11,
    LSLONL_PROGRAM_LENGTH:=12,
    LSLONL_PROG_END:=13,
    LSLONL_PROG_MEMO:=14,
    LSLONL_STOP_BRKPT:=15,
    LSLONL_CPU_STOP:=16,
    LSLONL_INT_ERROR:=17,
    LSLONL_SINGLE_STEP:=18,
    LSLONL_READY:=19,
    LSLONL_LOAD:=20,
    LSLONL_UNZUL_MODUL:=21,
    LSLONL_MEMORY_FULL:=22,
    LSLONL_NOT_LINKED:=23,
    LSLONL_DIV_BY_0:=24,
    LSLONL_DIAS_ERROR:=25,
    LSLONL_WAIT:=26,
    LSLONL_OP_PROG:=27,
    LSLONL_OP_INSTALLED:=28,
    LSLONL_OS_TOO_LONG:=29,
    LSLONL_NO_OPERATING_SYSTEM:=30,
    LSLONL_SEARCH_FOR_OS:=31,
    LSLONL_NO_DEVICE:=32,
    LSLONL_UNUSED_CODE:=33,
    LSLONL_MEM_ERROR:=34,
    LSLONL_MAX_IO:=35,
    LSLONL_MODULE_LOAD_ERROR:=36,
    LSLONL_GENERAL_OS_ERROR:=37,
    LSLONL_APPLMEM_ERROR:=38,
    LSLONL_OFFLINE:=39,
    LSLONL_APPL_LOAD:=40,
    LSLONL_APPL_SAVE:=41,
    LSLONL_VARAN_MANAGER_ERROR:=44,
    LSLONL_VARAN_ERROR:=45,
    LSLONL_APPL_LOAD_ERROR:=46,
    LSLONL_APPL_SAVE_ERROR:=47,
    LSLONL_ACCESS_EXCEPTION:=50,
    LSLONL_BOUND_EXCEEDED:=51,
    LSLONL_PRIVILEDGED_INSTRUCTION:=52,
    LSLONL_FLOATING_POINT_ERROR:=53,
    LSLONL_DIAS_RISC_ERROR:=60,
    LSLONL_INTERNAL_ERROR:=64,
    LSLONL_FILE_ERROR:=65,
    LSLONL_DEBUG_ASSERTION_FAILED:=66,
    LSLONL_REALTIME_RUNTIME:=67,
    LSLONL_BACKGROUND_RUNTIME:=68,
    LSLONL_USER_DEFINED_0:=95,
    LSLONL_USER_DEFINED_1:=96,
    LSLONL_USER_DEFINED_2:=97,
    LSLONL_USER_DEFINED_3:=98,
    LSLONL_USER_DEFINED_4:=99,
    LSLONL_C_INIT:=100,
    LSLONL_RUNRAM:=101,
    LSLONL_C_RUNROM:=102,
    LSLONL_C_RUNTIME:=103,
    LSLONL_C_READY:=104,
    LSLONL_C_OK:=105,
    LSLONL_C_UNKNOWN_CID:=106,
    LSLONL_C_UNKNOWN_CONSTR:=107,
    LSLONL_C_UNKNOWN_OBJECT:=108,
    LSLONL_C_UNKNOWN_CHNL:=109,
    LSLONL_C_WRONG_CONNECT:=110,
    LSLONL_C_WRONG_ATTR:=111,
    LSLONL_C_SYNTAX_ERROR:=112,
    LSLONL_C_NO_FILE_OPEN:=113,
    LSLONL_C_OUTOF_NEAR:=114,
    LSLONL_C_OUTOF_FAR:=115,
    LSLONL_C_INCOMPATIBLE:=116,
    LSLONL_C_COMPATIBLE:=117,
    LSLONL_LINKING:=224,
    LSLONL_LINKING_ERROR:=225,
    LSLONL_LINKING_DONE:=226,
    LSLONL_OP_BURN:=230,
    LSLONL_OP_BURN_FAIL:=231,
    LSLONL_OP_INSTALL:=232,
    LSLONL_USV_WAIT:=240,
    LSLONL_REBOOT:=241,
    LSLONL_LSL_SAVE:=242,
    LSLONL_LSL_LOAD:=243,
    LSLONL_CONTINUE:=252,
    LSLONL_PRERUN:=253,
    LSLONL_PRERESET:=254,
    LSLONL_CONNECTION_BREAK:=255,
    LSLONL_NOT_CONNECTED:=256
  )$UDINT;
  _VOIDL : USINT;
  _PVOIDL : ^_VOIDL;
  _SDDAXISSTATE : BDINT
  [
    1 NoHW,
    2 NoParameter,
    3 NotOnline,
    4 NotInitialized,
    5 SFFLimitationActive,
    6 DiagModeActive,
  ];
  _SDDUSERCMD :  //! <Type Comment="Type for user commands to the drive. See Server &apos;SDDCmdIntfc&apos; of the &apos;_DriveAxis&apos; class." Name="_SDDUSERCMD"/>
  (
    _SDDIDLE,  //! <Type Comment="default command" Name="_SDDUSERCMD._SDDIDLE"/>
    _SDDREADALL,  //! <Type Comment="read all parameters of the drive &#13;&#10;  and save the parameters in the SRAM or in the file.&#13;&#10;  If any parameter classes are connected to the class SDDMngBase,&#13;&#10;  the servers of the parameter classes are refreshed." Name="_SDDUSERCMD._SDDREADALL"/>
    _SDDINIT,  //! <Type Comment="Initialize the drive with the saved parameters." Name="_SDDUSERCMD._SDDINIT"/>
    _SDDURINIT,  //! <Type Comment="Initialize the drive with the parameters of the table.&#13;&#10;  (Lasal2 table, User Table or default table)" Name="_SDDUSERCMD._SDDURINIT"/>
    _SDDEXDATA,  //! <Type Comment="Export the actual drive parameter into an excel formatted file." Name="_SDDUSERCMD._SDDEXDATA"/>
    _SDDEXDATAXML:=6,  //! <Type Comment="Export the actual drive parameter into an xml formatted file." Name="_SDDUSERCMD._SDDEXDATAXML"/>
    _SDDIMDATAXML,  //! <Type Comment="Imports the drive parameter from an xml formatted file. User commands &quot;_SDDINIT&quot; must be called to transfer the data to the drive." Name="_SDDUSERCMD._SDDIMDATAXML"/>
    _SDDERROR  //! <Type Comment="This value is shown, when the user commands &quot;_SDDEXDATAXML&quot; or &quot;_SDDIMDATAXML&quot; failed. See Log-File for details. New user commands can be set in this state." Name="_SDDUSERCMD._SDDERROR"/>
  )$UDINT;
#pragma pack(push, 1)
  _TERMINAL_INFO : STRUCT
    ud_stno : UDINT;
    d_id : DINT;
    hd_iddiasbus : HDINT;
    ud_lines : UDINT;
    ud_charperline : UDINT;
    ud_keysinrow : UDINT;
    ud_keyrows : UDINT;
    ud_keyswithled : UDINT;
    b_hwbeep : UDINT;
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
  _XML_ATTRIBUTE : STRUCT
    Name : ^USINT;  //! <Type Comment="Name of the attribute" Name="_XML_ATTRIBUTE.Name"/>
    Value : ^USINT;  //! <Type Comment="Value of the attribute" Name="_XML_ATTRIBUTE.Value"/>
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
  _XML_ATTRIBUTE_LIST : STRUCT
    no : UDINT;  //! <Type Comment="Number of attributes" Name="_XML_ATTRIBUTE_LIST.no"/>
    pList : ^_XML_ATTRIBUTE;  //! <Type Comment="Pointer at the list of attributes" Name="_XML_ATTRIBUTE_LIST.pList"/>
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
  _XML_ELEMENT : STRUCT
    Name : ^USINT;  //! <Type Comment="Name of the element" Name="_XML_ELEMENT.Name"/>
    Attributes : _XML_ATTRIBUTE_LIST;  //! <Type Comment="Attribute list of the element" Name="_XML_ELEMENT.Attributes"/>
    pText : ^USINT;  //! <Type Comment="Pointer at the text of the element" Name="_XML_ELEMENT.pText"/>
    pChildren : ^_XML_ELEMENT;  //! <Type Comment="Pointer at the child-elements" Name="_XML_ELEMENT.pChildren"/>
    pFather : ^_XML_ELEMENT;  //! <Type Comment="Pointer at the father element" Name="_XML_ELEMENT.pFather"/>
    pNext : ^_XML_ELEMENT;  //! <Type Comment="Pointer at the next element at the same level" Name="_XML_ELEMENT.pNext"/>
    pPrevious : ^_XML_ELEMENT;  //! <Type Comment="Pointer at the previous element at the same level" Name="_XML_ELEMENT.pPrevious"/>
    isClosed : BOOL;  //! <Type Comment="True if element is already closed" Name="_XML_ELEMENT.isClosed"/>
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 4)
  _XML_FILE : STRUCT
    Header : ^USINT;  //! <Type Comment="Header in the XML file" Name="_XML_FILE.Header"/>
    MajorElement : ^_XML_ELEMENT;  //! <Type Comment="Major and first element in the XML file" Name="_XML_FILE.MajorElement"/>
  END_STRUCT;
#pragma pack(pop)
  DM_CPU_Types :
  (
    CPUNotIdentified,
    IPC_Text_CPU,
    IPC_800_CPU,
    IPC_1024_CPU,
    PCD_CPU,
    DSE_CPU,
    DCP_CPU,
    DCC080_CPU,
    DCP645_CPU,
    AK500_CPU,
    TSTROM_CPU,
    NoCPU_11,
    NoCPU_12,
    NoCPU_13,
    NoCPU_14,
    NoCPU_15,
    ELAN_CPU,
    ELAN800_CPU,
    WINPC_CPU,
    TERMINAL_CPU,
    DTC281_CPU,
    ELAN_TEXT_CPU,
    ELAN_800_CPU,
    ETT321_CPU,
    HERZ_CPU,
    ETT261_CPU,
    ETT431_CPU,
    WIN_PC98_CPU,
    WINPC_NT_CPU,
    WINIPC_98_CPU,
    WINIPC_NT_CPU,
    IPC_320_CPU,
    C_IPC_CPU,
    NoCPU_33,
    RK500_CPU,
    CCL721_CPU,
    CCL911_CPU,
    BDF2000_CPU,
    StandardPC_CPU,
    CCL081CET_CPU,
    CCL081_CPU,
    CCL722_CPU,
    DCL642_CPU,
    Teachbox_CPU,
    DTC081_CPU,
    DTC081_IP_CPU,
    ETV_CPU,
    HZS511_CPU,
    AUW11X_CPU,
    BDF2000_USB_CPU,
    DTC101_CPU,
    HZS515_CPU,
    CCP511_CPU,
    ETVEDGE_CPU,
    ARM_IMX6_CPU:=65537
  )$UDINT;
  DS402_Control : BDINT
  [
    1 SwitchOn,
    2 EnableVoltage,
    3 QuickStop,
    4 EnableOperation,
    5 OperationModeSpec1,
    6 OperationModeSpec2,
    7 OperationModeSpec3,
    8 ResetFault,
    9 Halt,
    10 Reserved1,
    11 Reserved2,
    12 ManufactureSpec1,
    13 ManufactureSpec2,
    14 ManufactureSpec3,
    15 ManufactureSpec4,
    16 ManufactureSpec5,
  ];
  DS402_State : BDINT
  [
    1 ReadyToSwitchOn,
    2 SwitchedOn,
    3 OperationEnabled,
    4 Fault,
    5 VoltageEnabled,
    6 QuickStop,
    7 SwitchOnDisabled,
    8 Warning,
    9 ManufactureSpec1,
    10 Remote,
    11 TargetReached,
    12 InternalLimitActive,
    13 OperationModeSpec1,
    14 OperationModeSpec2,
    15 ManufactureSpec2,
    16 ManufactureSpec3,
  ];
  FeSetup : BDINT
  [
    1 Valid,  //! <Type Comment="must be 1 to Start FileEx work" Name="FeSetup.Valid"/>
    2 FileorRam,  //! <Type Comment="0= work in File 1= Work File" Name="FeSetup.FileorRam"/>
    3 EnableChecksum,  //! <Type Comment="0=no Checksum; 1=Calculate Checksum, increased write access on the CF card" Name="FeSetup.EnableChecksum"/>
    4 Encrypt,  //! <Type Comment="0=no encryption; 1=encrypt file, increased write access on the CF card" Name="FeSetup.Encrypt"/>
  ];
  IO_FLAG : BINT  //! <Type Comment="Status Flag für IO Daten" Name="IO_FLAG"/>
  [
    1 WrongHW,  //! <Type Comment="Falsche Hardware verbunden" Name="IO_FLAG.WrongHW"/>
    2 NoHW,  //! <Type Comment="Keine Hardware verbunden" Name="IO_FLAG.NoHW"/>
    3 NoCalibration,  //! <Type Comment="Keine Kalibrierungsdaten im Modul-EEPROM" Name="IO_FLAG.NoCalibration"/>
    4 ParaChkWrong,  //! <Type Comment="Die Parameter-Checksumme ist falsch" Name="IO_FLAG.ParaChkWrong"/>
    5 PhysicHiLimit,  //! <Type Comment="IO ist am oberen physikalischen Limit" Name="IO_FLAG.PhysicHiLimit"/>
    6 PhysicLoLimit,  //! <Type Comment="IO ist am unteren physikalischen Limit" Name="IO_FLAG.PhysicLoLimit"/>
    7 Invert,  //! <Type Comment="Daten sind invertiert" Name="IO_FLAG.Invert"/>
    14 OnDummyMode,  //! <Type Comment="1 = Objekt ist im Dummymodus (nicht refreshed)" Name="IO_FLAG.OnDummyMode"/>
    15 NotConnected,  //! <Type Comment="1 = Objekt ist nicht verbunden" Name="IO_FLAG.NotConnected"/>
    16 PhysicAccessOff,  //! <Type Comment="1 = kein physikalischer Zugriff erlaubt" Name="IO_FLAG.PhysicAccessOff"/>
  ];
#pragma pack(push, 1)
  IO_State : STRUCT
    uiIO_Flags : IO_FLAG;
    uiChNo : UINT;
  END_STRUCT;
#pragma pack(pop)
  pHwBase : ^HwBase;
  pHwBaseCDIAS : ^HwBaseCDIAS;
  SafetyConfigStateType :
  (
    _ModuleNotFound,
    _SafetyClassOK,
    _ReinitConfig,
    _UnsafeVarNotFound,
    _ModFromCfgNotFound,
    _MemAllocFailed,
    _ReadFWVerFailed,
    _UnknownCfgError,
    _WaitForSynchronicity,
    _AsyncComError:=9,
    _DOsIncreasedRestartApp:=10,
    _LostPowerSupply:=11,
    _WrongSafetyHW:=12
  )$UDINT;
#pragma pack(push, 1)
  SafetyDiagInfo : STRUCT
    uControllerID : USINT;  //! <Type Comment="ID of µController (0 = µC1, else µC2)" Name="SafetyDiagInfo.uControllerID"/>
    ActErrorCode : USINT;  //! <Type Comment="actual error code" Name="SafetyDiagInfo.ActErrorCode"/>
    FirstErrorCode : USINT;  //! <Type Comment="code of first error that lead to an error state" Name="SafetyDiagInfo.FirstErrorCode"/>
    ReasonCode0 : UDINT;  //! <Type Comment="reason for error (meaning depends on actual error code)" Name="SafetyDiagInfo.ReasonCode0"/>
    ReasonCode1 : UDINT;  //! <Type Comment="reason for error (meaning depends on actual error code)" Name="SafetyDiagInfo.ReasonCode1"/>
  END_STRUCT;
#pragma pack(pop)
#pragma pack(push, 1)
  SafetyDiagState : STRUCT
    RunState : USINT;  //! <Type Comment=" 1..POST&#13;&#10; 2..SERVICE&#13;&#10; 4..ERROR&#13;&#10; 8..IDLE&#13;&#10;16..CHK_CFG&#13;&#10;32..OP_TEMP&#13;&#10;64..OP" Name="SafetyDiagState.RunState"/>
    ConfigState : USINT;  //! <Type Comment=" 1..INVALID&#13;&#10; 2..NOT_CONFIGURED&#13;&#10; 4..CONFIGURED_NOT_DEPLOYED_NOT_VERIFIED&#13;&#10; 8..CONFIGURED_AND_VERIFIED&#13;&#10;16..CONFIGURED_DEPLOYED_NOT_VERIFIED&#13;&#10;36..CONFIGURED_NOT_DEPLOYED_NOT_VERIFIED_DEV&#13;&#10;48..CONFIGURED_DEPLOYED_NOT_VERIFIED_DEV" Name="SafetyDiagState.ConfigState"/>
    LoginLevel : USINT;  //! <Type Comment="0..not logged in&#13;&#10;1..debug&#13;&#10;2..configuration&#13;&#10;3..general" Name="SafetyDiagState.LoginLevel"/>
    ErrorCounterIOState : UINT;  //! <Type Comment="Is increased on change of the error state of any input or output" Name="SafetyDiagState.ErrorCounterIOState"/>
  END_STRUCT;
#pragma pack(pop)
  t_e_SafetyMemState :
  (
    _ALL_OK,  //! <Type Comment="all memory settings are valid" Name="t_e_SafetyMemState._ALL_OK"/>
    _NOT_ACTIVE,
    _ASY_MEM_NOT_EQUAL,
    _ISO_MEM_NOT_EQUAL,
    _ASY_WR_SIZE_TOO_HIGH,
    _ASY_RD_SIZE_TOO_HIGH,
    _ISO_WR_SIZE_TOO_HIGH,
    _ISO_RD_SIZE_TOO_HIGH,
    _ISO_WR_SIZE_TOO_SMALL,
    _ISO_RD_SIZE_TOO_SMALL,
    _ASY_WR_INSTALL_ERROR,
    _ASY_RD_INSTALL_ERROR,
    _ISO_WR_INSTALL_ERROR,
    _ISO_RD_INSTALL_ERROR
  )$DINT;
  t_e_VaranErrors :
  (
    _ClassOk,
    _NotInitialized,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._NotInitialized"/>
    _CallBackError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._CallBackError"/>
    _RequiredError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._RequiredError"/>
    _RootError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._RootError"/>
    _NoHardware,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._NoHardware"/>
    _WrongHardware,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._WrongHardware"/>
    _CreateDOFailed,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._CreateDOFailed"/>
    _DirectAccessFailed,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._DirectAccessFailed"/>
    _PllError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._PllError"/>
    _TimeoutInInit,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._TimeoutInInit"/>
    _HardwareRequiredIRQ,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._HardwareRequiredIRQ"/>
    _HardwareNotRequiredIRQ,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._HardwareNotRequiredIRQ"/>
    _HardwareFatalErrorIRQ,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._HardwareFatalErrorIRQ"/>
    _ManagerError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._ManagerError"/>
    _DisableError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._DisableError"/>
    _EnableError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._EnableError"/>
    _MultipleError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._MultipleError"/>
    _SPIError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._SPIError"/>
    _ErrorBootImageFPGA,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._ErrorBootImageFPGA"/>
    _NoCDIASInterface,  //! <Type Comment="for CIV class" Name="t_e_VaranErrors._NoCDIASInterface"/>
    _EEPromError,  //! <Type Comment="for CIV class" Name="t_e_VaranErrors._EEPromError"/>
    _NoVaranInterface,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._NoVaranInterface"/>
    _MemoryFault,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._MemoryFault"/>
    _TimesliceError,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._TimesliceError"/>
    _TimesliceErrorIRQ,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._TimesliceErrorIRQ"/>
    _WatchdogError,  //! <Type Comment="for VaranMaster" Name="t_e_VaranErrors._WatchdogError"/>
    _VaranTimeError,  //! <Type Comment="for HwControl class" Name="t_e_VaranErrors._VaranTimeError"/>
    _DiasTimeError,  //! <Type Comment="for HwControl class" Name="t_e_VaranErrors._DiasTimeError"/>
    _DORamFull,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DORamFull"/>
    _PortNoLink,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._PortNoLink"/>
    _VaranDriverNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._VaranDriverNotExists"/>
    _WrongDOLType,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._WrongDOLType"/>
    _WrongRunStatus,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._WrongRunStatus"/>
    _DOHandleInvalid,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DOHandleInvalid"/>
    _DOCmdInvalid,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DOCmdInvalid"/>
    _ManagerNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._ManagerNotExists"/>
    _DOLAddressInvalid,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DOLAddressInvalid"/>
    _UnknownCommand,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._UnknownCommand"/>
    _ComponentNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._ComponentNotExists"/>
    _ClientNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._ClientNotExists"/>
    _CdiasEEPromNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._CdiasEEPromNotExists"/>
    _CdiasEEPromNoGrant,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._CdiasEEPromNoGrant"/>
    _CdiasEEPromNack,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._CdiasEEPromNack"/>
    _PortNotExists,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._PortNotExists"/>
    _PortIsUplink,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._PortIsUplink"/>
    _NoMutex,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._NoMutex"/>
    _NoTask,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._NoTask"/>
    _IDNotFound,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._IDNotFound"/>
    _IDNotInitialized,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._IDNotInitialized"/>
    _InvalidDeviceAddress,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._InvalidDeviceAddress"/>
    _CallbackNotHandled,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._CallbackNotHandled"/>
    _NoMem,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._NoMem"/>
    _NoLegacyWd,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._NoLegacyWd"/>
    _AdminDOLExecutionError,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._AdminDOLExecutionError"/>
    _DADOLExecutionError,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._DADOLExecutionError"/>
    _SPIFlashNoAccess,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._SPIFlashNoAccess"/>
    _ClientNotready,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._ClientNotready"/>
    _TimeoutVaran,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._TimeoutVaran"/>
    _UnknownFault,  //! <Type Comment="from VaranManager" Name="t_e_VaranErrors._UnknownFault"/>
    _DiasError,  //! <Type Comment="for CIC/DIV with Dias" Name="t_e_VaranErrors._DiasError"/>
    _DeviceError,  //! <Type Comment="for Varan hardwareclasses" Name="t_e_VaranErrors._DeviceError"/>
    _VaranTimeWarning,
    _OnlyASYSupported,
    _InvalidSerialNo,
    _CDIASRequiredError,
    _DIASRequiredError,
    _NoCalibDataFound,
    _ModuleFoundButManagerIsOff:=68,
    _InvalidConfguration,
    _ClientDisabled,
    _ClientCantEnable,
    _CdiasAddressInvalid,
    _SPIFlashInvalid,
    _SPIDOLIDInvalid,
    _SPIDOLInvalid,
    _SPIRequiredListError,
    _SPIChksumError,
    _ParameterInvalid,
    _DOTypeNotSupported,
    _DMAError,
    _PropertyIDInvalid,
    _PropertyValueInvalid,
    _DONumberOverflow,
    _APIUsageNotAllowed,
    _NodeTypeWrong,
    _DataLengthInvalid,
    _DOTypeInvalid,
    _OperationNotAllowed,
    _NodeNumberOverflow,
    _NoHandleFound,
    _TopologyNotAllowed
  )$UDINT;
#pragma pack(push, 1)
  t_s_ModulInfo : STRUCT
    Kennung : HINT;
    p_This : ^void;
  END_STRUCT;
#pragma pack(pop)
END_TYPE
